# Write your MySQL query statement below
SELECT P.PRODUCT_ID, P.PRODUCT_NAME
FROM PRODUCT AS P
JOIN (
    SELECT PRODUCT_ID, MIN(SALE_DATE) AS MIN_DATE, MAX(SALE_DATE) AS MAX_DATE
    FROM SALES
    GROUP BY PRODUCT_ID) AS T
ON P.PRODUCT_ID = T.PRODUCT_ID
WHERE T.MIN_DATE >= '2019-01-01' AND T.MAX_DATE <= '2019-03-31';
